import type { Tile } from '../types/game'

export const GAME_CONFIG = {
  CURRENCY: 'EGP',
  STARTING_BALANCE: 1500,
  GO_REWARD: 200,
}

export type EventOutcome =
  | { type: 'gain'; amount: number; title: string; description: string }
  | { type: 'loss'; amount: number; title: string; description: string }
  | { type: 'move'; target: number; title: string; description: string }
  | { type: 'jail'; target: number; title: string; description: string }

export const HAZAK_EVENTS: readonly EventOutcome[] = [
  {
    type: 'gain',
    amount: 150,
    title: 'Lottery Win',
    description: 'You won the local lottery! Collect 150.',
  },
  {
    type: 'gain',
    amount: 50,
    title: 'Found Wallet',
    description: 'You found a lost wallet on the street and kept the cash! Collect 50.',
  },
  {
    type: 'gain',
    amount: 200,
    title: 'Bank Error',
    description: 'Bank error in your favor! Collect 200.',
  },
  {
    type: 'loss',
    amount: 100,
    title: 'Speeding Ticket',
    description: 'You were caught speeding. Pay 100.',
  },
  { type: 'loss', amount: 50, title: 'Doctor Fee', description: 'Pay hospital fees. Pay 50.' },
  {
    type: 'loss',
    amount: 200,
    title: 'Scammed',
    description: 'You fell for a phishing scam! Pay 200.',
  },
  {
    type: 'move',
    target: 0,
    title: 'Advance to Start',
    description: 'Advance to Go! Collect 200.',
  },
  {
    type: 'move',
    target: 12,
    title: 'Vacation',
    description: 'Take a trip to the Vacation tile.',
  },
  {
    type: 'jail',
    target: 6,
    title: 'Go to Prison',
    description: 'Go directly to Prison. Do not pass Go, do not collect 200.',
  },
]

export const BOARD_DATA: Tile[] = [
  { id: 0, name: 'GO', type: 'SPECIAL' },
  {
    id: 1,
    name: 'Zamalek',
    type: 'PROPERTY',
    group: 'Cairo',
    price: 60,
    rent: [2, 10, 30, 90, 160, 250],
    housePrice: 50,
    color: '#8B4513',
  },
  { id: 2, name: 'Sodfa', type: 'EVENT' },
  {
    id: 3,
    name: 'Garden City',
    type: 'PROPERTY',
    group: 'Cairo',
    price: 60,
    rent: [4, 20, 60, 180, 320, 450],
    housePrice: 50,
    color: '#8B4513',
  },
  { id: 4, name: 'Income Tax', type: 'TAX', price: 100 },
  { id: 5, name: 'Cairo Airport', type: 'AIRPORT', price: 200 },
  { id: 6, name: 'Prison', type: 'SPECIAL' },
  {
    id: 7,
    name: 'Stanley',
    type: 'PROPERTY',
    group: 'Alex',
    price: 100,
    rent: [6, 30, 90, 270, 400, 550],
    housePrice: 50,
    color: '#87CEEB',
  },
  {
    id: 8,
    name: 'Agami',
    type: 'PROPERTY',
    group: 'Alex',
    price: 100,
    rent: [6, 30, 90, 270, 400, 550],
    housePrice: 50,
    color: '#87CEEB',
  },
  { id: 9, name: 'Hazak', type: 'EVENT' },
  {
    id: 10,
    name: 'Gleem',
    type: 'PROPERTY',
    group: 'Alex',
    price: 120,
    rent: [8, 40, 100, 300, 450, 600],
    housePrice: 50,
    color: '#87CEEB',
  },
  { id: 11, name: 'Suez Canal', type: 'UTILITY', price: 150 },
  { id: 12, name: 'Vacation', type: 'SPECIAL' },
  {
    id: 13,
    name: 'Karnak',
    type: 'PROPERTY',
    group: 'Luxor',
    price: 140,
    rent: [10, 50, 150, 450, 625, 750],
    housePrice: 100,
    color: '#FF0000',
  },
  { id: 14, name: 'Sodfa', type: 'EVENT' },
  {
    id: 15,
    name: 'Valley of Kings',
    type: 'PROPERTY',
    group: 'Luxor',
    price: 140,
    rent: [10, 50, 150, 450, 625, 750],
    housePrice: 100,
    color: '#FF0000',
  },
  {
    id: 16,
    name: 'Philae',
    type: 'PROPERTY',
    group: 'Luxor',
    price: 160,
    rent: [12, 60, 180, 500, 700, 900],
    housePrice: 100,
    color: '#FF0000',
  },
  { id: 17, name: 'EgyptAir', type: 'AIRPORT', price: 200 },
  { id: 18, name: 'Go To Prison', type: 'SPECIAL' },
  {
    id: 19,
    name: 'El Gouna',
    type: 'PROPERTY',
    group: 'Hurghada',
    price: 180,
    rent: [14, 70, 200, 550, 750, 950],
    housePrice: 100,
    color: '#FFD700',
  },
  { id: 20, name: 'Hazak', type: 'EVENT' },
  {
    id: 21,
    name: 'Sahl Hasheesh',
    type: 'PROPERTY',
    group: 'Hurghada',
    price: 200,
    rent: [16, 80, 220, 600, 800, 1000],
    housePrice: 100,
    color: '#FFD700',
  },
  { id: 22, name: 'Super Tax', type: 'TAX', price: 150 },
  { id: 23, name: 'Telecom Egypt', type: 'UTILITY', price: 150 },
]
